### ISSUE TITLE
New pools not found by the SDK

### ISSUE THREAD

**Issue by mcfriend99** [raydium-io/raydium-sdk-V2#11]
I use the code below to get pools from mint address and it works perfectly for tokens older than 20 minutes, but for new tokens it always returns an empty set:

```js
const { data } = (await raydium.api.fetchPoolByMints({ 
    mint1: address, 
    mint2: NATIVE_MINT,
    type: PoolFetchType.All,
  }))
```

Data always comes up as an empty array as the original response reads: `{ count: 0, data: [], hasNextPage: false }`.

How do we resolve this??

**Comment by cruzshia** [comment]
Api needs time to initialize and sync pool data, not real time update for new created pools

**Comment by mcfriend99** [comment]
So how do we fetch pool information for new pools given the ID?? Without that capacity, the v2 is completely redundant because this works perfectly with the v1 SDK.

**Comment by cruzshia** [comment]
V2 sdk is built on api, is sdk v1 works for you, you can use it instead. They are doing exactly the same thing.

**Comment by mcfriend99** [comment]
I don't agree with the last statement. I can see a lot of simulateTransaction issues we've had to work around not present in the v2 version all together. So in summary, you're saying there's no way to get pool information for new tokens without using the v1 sdk?? Just asking so I can know if I should start working in that approach.
