### ISSUE TITLE
Always getting insufficient balance no matter what I use as amountIn

### ISSUE THREAD

**Issue by mcfriend99** [raydium-io/raydium-sdk-V2#12]
The issue is as it presents itself. I'm using the code as it is in the demo application with 

```js
const out = raydium.liquidity.computeAmountOut({
    poolInfo: {
      ...poolInfo,
      baseReserve: pool.baseReserve,
      quoteReserve: pool.quoteReserve,
      status: pool.status.toNumber(),
      version: 4,
    },
    amountIn: new BN(100000),
    mintIn: inputToken, // swap mintB -> mintA, use: poolInfo.mintB.address
    mintOut: outputToken, // swap mintB -> mintA, use: poolInfo.mintA.address
    slippage, // range: 1 ~ 0.0001, means 100% ~ 0.01%
  })

  const { transaction } = await raydium.liquidity.swap({
    poolInfo,
    amountIn: new BN(100000),
    amountOut: out.minAmountOut, // out.amountOut means amount 'without' slippage
    fixedSide: 'in',
    inputMint: inputToken, // swap mintB -> mintA, use: poolInfo.mintB.address
    associatedOnly: false,
    txVersion,
    // optional: set up priority fee here
    // computeBudgetConfig: {
    //   units: 600000,
    //   microLamports: 100000000,
    // },
  })
```

No matter what I set the amount in as I always get insufficient balance whether with transaction simulation enabled or not. Even when I set the amount to 0.0001 SOL (100000 lamports) and I have as much as 5 SOLs in my wallet balance, I still get insufficient funds error.

**Comment by cruzshia** [comment]
Make sure you pass correct input and outMint for compute and swap function, no issues was found.

**Comment by mcfriend99** [comment]
I've debugged this severally, I've even hardcoded it based on the values returned from `raydium.api.fetchPoolById` and It's the same. I've set the values of input and output mint directly from what was returned by `fetchPoolById`. 

Same behavior. 

While I'm reporting this issue, more than 6 other members of my team are having the same issue with their own implementation too.

**Comment by cruzshia** [comment]
Please paste your full code here and what's the sdk version are you used?

**Comment by mcfriend99** [comment]
You were right. The input and output mint were swapped by another library we all shared.
