### ISSUE TITLE
 Does this sdk support Raydium V4?

### ISSUE THREAD

**Issue by chatTeap** [raydium-io/raydium-sdk-V2#13]
Does this sdk support Raydium V4?

**Comment by mcfriend99** [comment]
I tested and Yes it does.

**Comment by chatTeap** [comment]
> I tested and Yes it does.

hi, thanks for your reply. I understand that raydium v4 can create pool without openbook, but when I use createAmmPool in raydium-sdk-V2-demo, I still need marketInfo, what's the reason?

**Comment by chatTeap** [comment]
> pools without market info is `CPMM` not `createAmmPool`, please check sdk demo code here: https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/cpmm/createCpmmPool.ts



> pools without market info is `CPMM` not `createAmmPool`, please check sdk demo code here: https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/cpmm/createCpmmPool.ts

Hello, how much does create CpmmPool cost?

**Comment by chatTeap** [comment]
> for more pool creation info, please check: https://docs.raydium.io/raydium/pool-creation/pool-creation-fees and https://docs.raydium.io/raydium/pool-creation/creating-a-constant-product-pool

I see, thank you very much for your patience!
