### ISSUE TITLE
installing raydium-sdk-V2 on a react project crashes the app

### ISSUE THREAD

**Issue by sponge-babe** [raydium-io/raydium-sdk-V2#14]
i used yarn to install raydium-sdk-v2: 0.1.30-alpha
and tried to initiate the raydium sdk with the following code:
`Raydium.load({
      connection,
    })`
    
    and immediately i was thrown this error in screenshot:
    
![image](https://github.com/raydium-io/raydium-sdk-V2/assets/156430154/223286fc-8fb3-4785-bf05-ca5cc561f93e)

**Comment by cruzshia** [comment]
this might cause by your package.json setting, but to prevent this, push a new version not to use this, install latest version and try it.
https://github.com/raydium-io/raydium-sdk-V2/commit/3bafa38230bb3a4beb9140835f24fd454cc954ef
