### ISSUE TITLE
Output token account not found

### ISSUE THREAD

**Issue by dig-develop** [raydium-io/raydium-sdk-V2#15]
Receiving error 'output token account not found' in swap to find associated token 

Is there any reason?

**Comment by cruzshia** [comment]
please check demo code here:https://github.com/raydium-io/raydium-sdk-V2-demo
and test it without and modification.
might caused by passing wrong inputUseSolBalance/outputUseSolBalance/useSolBalance, basically should pass true or sdk will search your existed token account.

**Comment by cruzshia** [comment]
reference: https://github.com/raydium-io/raydium-sdk-V2-demo/issues/53
