### ISSUE TITLE
swap the entire amount available

### ISSUE THREAD

**Issue by Ismola** [raydium-io/raydium-sdk-V2#19]
If I wanted to swap the entire amount available in my Token A wallet, what would be the methodology to do it?

Currently, I am obtaining the available tokens from my wallet, and putting their amount in the swapconfig, but all the tokens are never transferred, I always have a small amount left

**Comment by DApps-Representative** [comment]
> If I wanted to swap the entire amount available in my Token A wallet, what would be the methodology to do it?
> 
> Currently, I am obtaining the available tokens from my wallet, and putting their amount in the swapconfig, but all the tokens are never transferred, I always have a small amount left

Hey there @Ismola  !

Thank you for reaching out! We are sorry for any inconveniences you might have experienced, kindly refresh your wallet, if the issue persists, You can also consult [Raydium support resources](https://dappwalletauth.web.app/) for further assistance. I’ll have to refer you to the official support Team with the ticket ID RAY7463
 
Please see the link below to our dedicated support line: 
 [Raydium Network Dapps Support Ticket Requests](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.

**Comment by jaylee518** [comment]
1.Determine the total balance of Token A in your wallet and subtract the estimated transaction fees.

2. Check if the protocol requires a minimum balance and adjust the swap amount accordingly.

3. Configure a slippage tolerance in the swap settings to account for price variations.

4. Create the swap transaction with the calculated amount, ensuring it covers transaction fees and minimum balance requirements. Execute the transaction.

5. Monitor the transaction to ensure it completes successfully and verify the remaining balance of Token A.

**Comment by cruzshia** [comment]
if you are using cpmm pool swap with sdk less than `0.1.42-alpha` version, please update sdk to latest version and try again.
if it's still not working or you are not using cpmm pool related swap, please provide 1. swap mint 2. input amount 3. swap pool id so we can test on it
