### ISSUE TITLE
Error: Number can only safely store up to 53 bits from computeAmountOut

### ISSUE THREAD

**Issue by mcfriend99** [raydium-io/raydium-sdk-V2#21]
Hi,

I have the code below which should compute amount out from given pool. It works sometimes, but half the time I keep getting the error `Number can only safely store up to 53 bits`.

Here's the code:

```js
const out = raydium.liquidity.computeAmountOut({
    poolInfo: {
      ...poolInfo,
      baseReserve,
      quoteReserve,
      status,
      version: 4,
    },
    amountIn: new BN(amountIn),
    mintIn: mintIn.address,
    mintOut: mintOut.address,
    slippage: 0.01, // range: 1 ~ 0.0001, means 100% ~ 0.01%
  })
```

The amount is fixed at 100k lamports for all transactions so that should not be outside the range of big numbers (53 bits).

My code is based on [https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/amm/swap.ts](https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/amm/swap.ts) with the variables renamed but no other difference whatsoever.

**Comment by cruzshia** [comment]
could you share the full code? which pool and amountIn...etc.
also you can try print logs to see is there any data exceed 53 bits.

**Comment by cruzshia** [comment]
I guess if you are swapping for a pair like 100K sol to a meme coin with value like 0.000000001 usd, and the `out.minAmountOut` might overflow.

**Comment by mcfriend99** [comment]
I already pointed to the source verbatim in the post. Since the error happens on the function that should return the `minAmountOut`, I can't log it because that's exactly the function raising an exception.

**Comment by cruzshia** [comment]
could you share more info? which pool and amountIn...etc.
and also print input params like 
```
poolInfo: {
      ...poolInfo,
      baseReserve,
      quoteReserve,
      status,
      version: 4,
    },
```

to see whether the data is valid.

**Comment by mcfriend99** [comment]
This is the complete error message:

```
Error: Number can only safely store up to 53 bits
    at assert (/home/ubuntu/MyProject/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/home/ubuntu/MyProject/node_modules/bn.js/lib/bn.js:547:7)
    at Pr.computeAmountOut (/home/ubuntu/MyProject/node_modules/@raydium-io/raydium-sdk-v2/lib/index.js:1:259520)
    at raydiumSwap (/home/ubuntu/MyProject/raydium-swap.js:405:55)
```

I think the library should use `parseFloat(bn.toString())` instead of `bn.toNumber()`. I've found the later to fail a lot of times in this age of memecoins.

**Comment by mcfriend99** [comment]
The pool is `3rjdW2acpqdyf8qapEHwMoAzQUsfGjPbG3hjmJWaC6vN` and the amount is `100k` lamports as said in the original post.

**Comment by cruzshia** [comment]
I didn't get any error even give  100 * 10 ** 9 input amount, 
<img width="907" alt="image" src="https://github.com/user-attachments/assets/bd4c24d9-ca5e-4d66-9bc7-0eb17b3e9e97">

**Comment by cruzshia** [comment]
also you can check we didn't use any parseFloat or toNumber in calculation here https://github.com/raydium-io/raydium-sdk-V2/blob/master/src/raydium/liquidity/liquidity.ts#L723, which I pass fixed pool `version: 4` to raydium.liquidity.computeAmountOut, so all `xxx.toNumber` won't be reached.
