### ISSUE TITLE
Incorrect comment causing program to break in dev mode

### ISSUE THREAD

**Issue by alex-js-ltd** [raydium-io/raydium-sdk-V2#22]
Description:

There is an incorrect comment in the raydium-sdk-V2-demo/src/cpmm/createCpmmPool.ts file which causes the program to break. The current comment is:

// devnet: CREATE_CPMM_POOL_FEE_ACC.CREATE_CPMM_POOL_PROGRAM

Proposed Solution:

// devnet: DEVNET_PROGRAM_ID.CREATE_CPMM_POOL_PROGRAM or DEV_CREATE_CPMM_POOL_FEE_ACC

Thank you! 🙏

**Comment by cruzshia** [comment]
OK, thanks for pointing out! Will fix comment later, next time you can raise issue in demo repo🙏
