### ISSUE TITLE
Cannot be swapped.

### ISSUE THREAD

**Issue by BCIGRA** [raydium-io/raydium-sdk-V2#24]
Hello, I would like to inform you that there are some tokens that ended up failing in the simulation and cannot be swapped.

![Screenshot 2024-08-01 125939](https://github.com/user-attachments/assets/29eb7845-6f69-4bca-a3c7-cc7354512dc0)

![Screenshot 2024-08-01 125732](https://github.com/user-attachments/assets/0be8449f-6332-47f5-93d4-6d406269b18e)

**Comment by cruzshia** [comment]
our swap txs are generated from api, if your tokens can't swap in UI, you can open support tickets in discord, thank you.
