### ISSUE TITLE
Missing Exports from @raydium-io/raydium-sdk-v2

### ISSUE THREAD

**Issue by MrGranday** [raydium-io/raydium-sdk-V2#30]
The errors indicate that the SDK does not export Liquidity, TOKEN_PROGRAM_ID, SPL_ACCOUNT_LAYOUT, and other specified exports.

i have used 
import { TOKEN_PROGRAM_ID, Token, AccountLayout } from '@raydium-io/raydium-sdk-v2';

and installed like this 
yarn add @raydium-io/raydium-sdk-v2@latest

**Comment by cruzshia** [comment]
you should import AccountLayout/TOKEN_PROGRAM_ID from '@solana/spl-token'
