### ISSUE TITLE
How to close ws errror ws error: Unexpected server response: 200

### ISSUE THREAD

**Issue by TIANJINFENG** [raydium-io/raydium-sdk-V2#31]
Each transaction creates a ws, causing the memory usage to increase continuously

ws errror ws error: Unexpected server response: 200

**Comment by cruzshia** [comment]
No issues was found in sdk, maybe should check your rpc node.

**Comment by cruzshia** [comment]
Sdk only subscribe token account change(https://github.com/raydium-io/raydium-sdk-V2/blob/master/src/raydium/account/account.ts#L124 ) when needs to fetch token account data, no other usage of websocket.
And the error was returned by your rpc.
