### ISSUE TITLE
Several functions under raydium.api seems not working?

### ISSUE THREAD

**Issue by TechSkieur** [raydium-io/raydium-sdk-V2#36]
Sample Code:
```
    const raydium = await Raydium.load({
        owner: wallet,
        connection: new Connection("https://api.mainnet-beta.solana.com", "confirmed"),
        cluster: "mainnet",
        disableFeatureCheck: true,
        disableLoadToken: true,
        blockhashCommitment: "confirmed",
      });
    const props: FetchPoolParams = { type: PoolFetchType.All, sort: "apr24h", order: "desc", page: 0, pageSize: 50 };
    const data = await raydium.api.getPoolList(props);
    console.log(data);
```
Tried function getPoolList, getTokenInfo, fetchPoolByMints, all not working, return null or zero data, which is not right. But if using function getTokenList, then results can be returned. Not sure why is that and potentially where goes wrong? Tested also with devnet

**Comment by cruzshia** [comment]
api doesn't support devent

**Comment by TechSkieur** [comment]
@cruzshia thanks for checking. But in fact I tried with mainnet, check my code sample above, still not return desired results...could you explain a bit more?

**Comment by TechSkieur** [comment]
@cruzshia thanks! And one more question, if wanna retrieve Pool list for devnet, is there a way I can do that by calling some other methods or?

**Comment by cruzshia** [comment]
for api no, not supported.
if you really want to get devent pool list, you can take a reference code here: https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/trade/routeSwap.ts#L41 by calling rpc.
you should use a paid rpc to get those info cuz the data is really huge and just some basic info,

**Comment by TechSkieur** [comment]
@cruzshia thanks! You explained me everything I need!
