### ISSUE TITLE
Interesting behavior: raydium.api.fetchPoolById cannot return poolInfo while raydium.liquidity.getPoolInfoFromRpc can

### ISSUE THREAD

**Issue by TechSkieur** [raydium-io/raydium-sdk-V2#39]
This is tested on **Mainnet**. I am trying to monitor new pool created. 

If using await raydium.liquidity.getPoolInfoFromRpc({poolId}), pool info can be fetched; If using await raydium.api.fetchPoolById({ ids: poolId }), return NULL. I could not figure out why...Pool id is: EgqAuwQnSW6M6ZFHxTj5f8mbLuv2Rm2WUaZ88M3KWN98

check screenshot
![Uploading Screenshot 2024-09-27 at 22.42.40.png…]()

**Comment by TechSkieur** [comment]
@cruzshia any thought? :)

**Comment by cruzshia** [comment]
Api has some data delay so needs minutes to sync data, if you need new pool data please get from rpc.

**Comment by TechSkieur** [comment]
@cruzshia got it! I guess so as well, now got confirmation from your side:) thanks a lot bro!
