### ISSUE TITLE
how to compute pool size

### ISSUE THREAD

**Issue by TechSkieur** [raydium-io/raydium-sdk-V2#40]
The question comes from one line of code I found somewhere from internet, it's a way of computing pool size:

`const poolSize = new TokenAmount(quoteToken, poolState.swapQuoteInAmount, true);`

I don't quite get it why computing like this. Could you explain to me?

According to my understanding, if quote token is WSOL, swapQuoteInAmount indicates how many SOL gets swapped into Pool? So it's like let's say when pool gets created, initial SOL liquidity is 10 SOL, now with time being, SOL liquidity in the pool increases to 20 SOL => swapQuoteInAmount would be something like 10 SOL. I guess my understanding on field swapQuoteInAmount is somewhat wrong...

thanks for answering

**Comment by TechSkieur** [comment]
@cruzshia could you help to answer my latest question..thanks..

**Comment by cruzshia** [comment]
I don't know where you found these code and it's not provided by us, so I can't explain it.
further more, I suggest you read code from our official demo repo and relative code from sdk repo, thanks.
https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/clmm/swap.ts
https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/amm/swap.ts
https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/cpmm/swap.ts

**Comment by TechSkieur** [comment]
okay @cruzshia thanks, just one quick question, is my understanding on swapQuoteInAmount correct or wrong? What's your insights on this field
