### ISSUE TITLE
Can I use ApiPoolInfoV4?

### ISSUE THREAD

**Issue by ucbarton** [raydium-io/raydium-sdk-V2#44]
I want to keep track of the newly created pools on Raydium, to do this there is a getPoolList() method that returns ApiV3PoolInfoItem data. There is also an ApiPoolInfoV4 interface in the API, but I can't use it, even though it contains more appropriate data. Are you going to add this interface for use when retrieving pool data?

**Comment by ParzifaL-03** [comment]
i have the same problem too

**Comment by ParzifaL-03** [comment]
@ucbarton are you already find it?

**Comment by cruzshia** [comment]
There's no PoolInfoV4, and our api "doesn't support provide realtime new pool" data, it needs sometime to sync, also sdk doesn't watch for newly created pool too, maybe. you can try loop fetching all pool data or watch program by AMM/CLMM/CPMM to check whether there's a new pool (just a concept for you)

**Comment by ucbarton** [comment]
> @ucbarton are you already find it?

I realized that this interface is not used and reconsidered the approach, I decided to do through solana web3 library. What are you doing? It would be interesting to communicate and share experience.
