### ISSUE TITLE
why allways ping the rpc

### ISSUE THREAD

**Issue by violet-evergarden** [raydium-io/raydium-sdk-V2#49]
<img width="911" alt="image" src="https://github.com/user-attachments/assets/e38abbfa-4310-43d8-9738-754e9d8fe40a">

**Comment by violet-evergarden** [comment]
const raydium = await Raydium.load({
    owner,
    connection,
    cluster: "mainnet",
    disableFeatureCheck: true,
  });

  const data = await raydium.api.fetchPoolById({
    ids: poolId,
  });
  const poolInfo = data[0] as ApiV3PoolInfoStandardItemCpmm;
  const rpcData = await raydium.cpmm.getRpcPoolInfo(poolInfo.id, true);

  const inputAmount = new BN(amountIn);
  let baseIn ;
  let swapResult;
  console.log(mintIn)
  if (poolInfo.mintA.address === mintIn) {
    // swap pool mintA for mintB
    baseIn = true;
    swapResult = CurveCalculator.swap(
      inputAmount,
      rpcData.baseReserve,
      rpcData.quoteReserve,
      rpcData.configInfo!.tradeFeeRate
    );
  } else {
    console.log(mintOut)
    baseIn = false;
    swapResult = CurveCalculator.swap(
      inputAmount,
      rpcData.quoteReserve,
      rpcData.baseReserve,
      rpcData.configInfo!.tradeFeeRate
    );
  }

**Comment by cruzshia** [comment]
sdk doesn't call ping method, that's solana library's mechnism.
