### ISSUE TITLE
BUG 

### ISSUE THREAD

**Issue by violet-evergarden** [raydium-io/raydium-sdk-V2#50]
Happens when I use this function

<img width="744" alt="image" src="https://github.com/user-attachments/assets/8dafbade-7ab0-4541-964e-d657e0225091">
<img width="492" alt="image" src="https://github.com/user-attachments/assets/cf8e4199-aa9d-4a07-875d-afa9080c06f6">

My guess is that it uses a deprecated method in the Solana package.

<img width="861" alt="image" src="https://github.com/user-attachments/assets/b61b5441-41bb-4480-b91b-a9deb94e3f6e">

**Comment by cruzshia** [comment]
updated
https://github.com/raydium-io/raydium-sdk-V2/commit/743144948fa36f1bfa0dc3f31d6ad9f2eee29bc0
