### ISSUE TITLE
raydiumSdk  routeSwap with 429 Too Many Requests

### ISSUE THREAD

**Issue by mianshenglee** [raydium-io/raydium-sdk-V2#55]
i'm using raydiumSdk to do routeSwap like the demo :https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/trade/routeSwap.ts, but when the program exec raydiumSdk.tradeV2.fetchSwapRoutesData, it will cause this error: Server responded with 429 Too Many Requests.  Retrying after 500ms delay..., at last throw this exception : Error: failed to get info for multiple accounts, RPC_ERROR, 429 Too Many Requests. 

since my rpc is paid , so i think the sdk do calling rpc too many times some way.

 i check out the sdk source and find getMultipleAccountsInfo function, this :await Promise.all(_batch.map(async (i) => await (connection as any)._rpcBatchRequest(i))).  it will call rpc many times ....  why the sdk do that ?  

any one can help me out how to solve this problem?

**Comment by cruzshia** [comment]
I think you have to upgrade your pard rpc subscription plan, all rpc call are needed when generating route swap
