### ISSUE TITLE
api.sendTxToJito

### ISSUE THREAD

**Issue by YoleYu** [raydium-io/raydium-sdk-V2#56]
is there any sample about sendTxToJito?

Thanks

**Comment by cruzshia** [comment]
it's not open to use yet, will add demo when we start support it

**Comment by YoleYu** [comment]
I'm using your SDK which is the most reliable one. However, I'm encountering an issue while integrating with Jito.

I'm following these steps:

1.  _MakeTxData_: Use _raydium.liquidity.swap_ to get the necessary transaction data.
2.    Use the [jito_tips_tx_executor ](https://github.com/hexnome/solana-memecoin-pumpfun-cli/blob/main/src/Transactions/jito_tips_tx_executor.js) from another repo, 
`     let latestBlockhash = await connection.getLatestBlockhash();
    const res = await jito_executeAndConfirm(x.transaction, wallet, latestBlockhash,  process.env.JITO_FEE);`

But the logs says "No Jito validators accepted the tx"

Could you please assist me in identifying the cause of this issue?  Must I use the the same latestBlockhash which get inside raydium.liquidity.swap?

**Comment by YoleYu** [comment]
@cruzshia @TimonPeng @

**Comment by cruzshia** [comment]
as I said, we are not using jito for this moment, if you want to use it, please DYOR
https://docs.jito.wtf/lowlatencytxnsend/#api
