### ISSUE TITLE
Error "custom program error: 0x1799" when attempting to swap with specific route

### ISSUE THREAD

**Issue by BCIGRA** [raydium-io/raydium-sdk-V2#57]
### Description:
I encountered an issue while trying to perform a swap using a route suggested by Raydium. The transaction failed with the following error logs:

```
Program CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK failed: custom program error: 0x1799
Program routeUGWgWzqBWFcrCfv8tritsqukccJPu3q5GPP3xS failed: custom program error: 0x1799
```

Below are the details of the swap route used:

```
Target swap route: {
  input: '0.008',
  output: '0.038406088',
  minimumOut: '0.038214058',
  profit: '0.030164058',
  priceImpact: '9.15',
  middleToken: '7i5XE77hnx1a6hjWgSuYwmqdmLoDJNTU1rYA6Gqx7QiE',
  trade: 'https://raydium.io/swap/?inputMint=sol&outputMint=7i5XE77hnx1a6hjWgSuYwmqdmLoDJNTU1rYA6Gqx7QiE',
  swapType: 'route',
  routes: 'CLMM 7WNxKJiZUtoDA3ebre8Zb3Xg8Lh63XBzd5uXVUFvrmSN 0 -> AMM H2im2CtUNpwDiWdDShdALgq7kZnXe6aT1mNZtjPCQU22 6'
}
```

### Expected Result:
The swap transaction should be successful using the suggested route.

---

### Actual Result:
The transaction fails with the following error logs:
```
Program CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK failed: custom program error: 0x1799
Program routeUGWgWzqBWFcrCfv8tritsqukccJPu3q5GPP3xS failed: custom program error: 0x1799
```

**Comment by cruzshia** [comment]
test src/trade/routeSwap, it recommend swap through amm pool
the route you provided it's not valid cuz clmm pool has 0 liquidity, also you can't swap through pool with same mints
please use the route suggested by sdk
<img width="546" alt="image" src="https://github.com/user-attachments/assets/80eb38b1-2609-41b4-9c41-9b6394903268">
