### ISSUE TITLE
Update @solana/web3.js to 1.95.8 (vulnerability detected)

### ISSUE THREAD

**Issue by milorddev** [raydium-io/raydium-sdk-V2#61]
A vulnerability has been found in 1.95.6 and 1.95.7 versions

https://github.com/advisories/GHSA-jcxm-7wvp-g6p5

https://github.com/solana-labs/solana-web3.js/security/advisories/GHSA-jcxm-7wvp-g6p5

To be on the safe side, just informing you guys

**Comment by cruzshia** [comment]
we do aware of this issue, thanks
