### ISSUE TITLE
Which code to use, addLiquidity to Raydium via typescript

### ISSUE THREAD

**Issue by magnomilk100** [raydium-io/raydium-sdk-V2#62]
Dear Shia Cruz,

I have started trying creating a Raydium pool to add liquidity around 7 months ago. I faced few issues, you helped me, I got involved with other tasks and now I am going to this last part of the code again. I am giving this context because I was working probably with old code and now I am getting erro. I used codes from raydium-sdk-V2-demo. 

Now, I dont know which code I should really use...

This is my issue:
Kindly help me with this issue, already 1 week trying different things...

I am trying to create a liquidity pool in Raydium.
For this I created a market with createMarket.ts under amm folder.
I then created the pool with createAmmPool.ts.

Now I get error when trying to add the liquidity pool. The errors says about slippage, I have tried several configuration from 1 to 80% and doesnt work, the error is always the same. I see also mentioning something regrading Unknown Program, I am running it on Devnet.

This is the script:
src/amm/addLiquidity.ts

**This is the error when running the typescript code:**
  signature: 'NGJbgKRBBt5w2mk6HaBAqdm2pTiw43QXDGmcKfY34cv3oHxkcL8vBAsaa1EhC45S2i8bHFkYzUFDgLM7eENKBK7',
  transactionMessage: 'Status: ({"err":{"InstructionError":[4,{"Custom":30}]}})',
  
  
**In  explorer.solana.com, shows me this error to the transaction:**
  [Unknown Program (HWy1jotHpo6UqeQxx49dpYYdQB8wj9Qk9MdxwjLvDHB8) Instruction](https://explorer.solana.com/tx/55Ggw5Hkf7PcFjUJP3PRs37dgy63vCGyKMWCKUb3TCDLppMXshMVATD8tMng4VGPEPjVovFfvLWDJxzFNRVGmzAq?cluster=devnet#ix-3)
> Program logged: "ray_log: AQDh9QUAAAAAwgEAAAAAAAAAAAAAAAAAAABA5ZwwEgAAAGXNHQAAAAAA6HZIFwAAAABlzR0AAAAAAAAAAAAAAAAAgPQg5rUAAAAAAAAAAAAAAOH1BQAAAADECQAAAAAAAAAAAAAAAAAA"
> Program logged: **"Error: exceeds desired slippage limit"**
> Program consumed: 34938 of 796407 compute units
> Program returned error: "custom program error: 0x1e"

**Comment by cruzshia** [comment]
demo code has bug and it has been fixed.
https://github.com/raydium-io/raydium-sdk-V2-demo/commit/7e89fdea1902fc9af3decc9a556b60b5a094228d
you can use demo code to write correct code now

**Comment by magnomilk100** [comment]
I will test then. Thanks so much for the info!!!! Have a great day.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
