### ISSUE TITLE
'"@solana/web3.js"' has no exported member named 'GetProgramAccountsResponse'. Did you mean 'GetProgramAccountsConfig'?

### ISSUE THREAD

**Issue by converttt** [raydium-io/raydium-sdk-V2#63]
"@raydium-io/raydium-sdk-v2": "^0.1.93-alpha"
"@solana/web3.js": "^1.87.6"

import { PublicKey, AccountInfo, RpcResponseAndContext, GetProgramAccountsResponse } from '@solana/web3.js';
in @raydium-io/raydium-sdk-v2/lib/raydium/account/util.d.ts

**Comment by cruzshia** [comment]
version 1.95.3 has GetProgramAccountsResponse, please check your sdk version

**Comment by converttt** [comment]
thanks, еру method is there, but it still says there is no such exported  member

**Comment by cruzshia** [comment]
maybe you you should open issue in @solana/web3.js repo
we don't host this library and also please ensure you are using correct version of @solana/web3.js sdk
