### ISSUE TITLE
Absurdly high fees for swaping

### ISSUE THREAD

**Issue by LukasKarer** [raydium-io/raydium-sdk-V2#64]
I am using the example for the wapping, which also works for me. but produces absurdly high fees [TX](https://solscan.io/tx/5EUrATSVxaUexwLkyfcUM4oqwMk9H8rSFuBKb55iVicnx2u2YmKVeSnywNSEduQqXP6pyXq2xYh7ikj31DZbkWvR). Does anyone have an idea how to fix this problem. The following code is Javascript, not Typescript, but i guess the shouldnt matter

`const amount = 10000;
      const slippage = 0.5;
      const txVersion = 'V0';
      const isV0Tx = txVersion === 'V0';

      //const [isInputSol, isOutputSol] = [inputMint === this.WSOL_ADDRESS.toBase58(), outputMint === this.WSOL_ADDRESS.toBase58()]
      const isInputSol  = isBuy;
      const isOutputSol  = !isBuy;
      const inputMint = isBuy ? this.WSOL_ADDRESS.toBase58() : tokenMintPubKey.toBase58();
      const outputMint = isBuy ? tokenMintPubKey.toBase58() : this.WSOL_ADDRESS.toBase58();

      const { tokenAccounts } = await this.fetchTokenAccountData()
      const inputTokenAcc = tokenAccounts.find((a) => a.mint.toBase58() === inputMint)?.publicKey
      const outputTokenAcc = tokenAccounts.find((a) => a.mint.toBase58() === outputMint)?.publicKey

      if (!inputTokenAcc && !isInputSol) {
        console.error('do not have input token account')
        return
      }

      // get statistical transaction fee from api
      /**
       * vh: very high
       * h: high
       * m: medium
       */
      const fees = await axios.get(`${API_URLS.BASE_HOST}${API_URLS.PRIORITY_FEE}`);

      const { data: swapResponse } = await axios.get(
        `${API_URLS.SWAP_HOST}/compute/swap-base-in?inputMint=${inputMint}&outputMint=${outputMint}&amount=${amount}&slippageBps=${slippage * 100}&txVersion=${txVersion}`
      );

      const { data: swapTransactions } = await axios.post(
        `${API_URLS.SWAP_HOST}/transaction/swap-base-in`, {
            computeUnitPriceMicroLamports: String(fees.data.data.default.h),
            swapResponse,
            txVersion,
            wallet: this.ownWallet.publicKey.toBase58(),
            wrapSol: isInputSol,
            unwrapSol: isOutputSol,
            inputAccount: isInputSol ? undefined : inputTokenAcc?.toBase58(),
            outputAccount: isOutputSol ? undefined : outputTokenAcc?.toBase58(),
        }
      );

      const allTxBuf = swapTransactions.data.map((tx) => Buffer.from(tx.transaction, 'base64'))
      const allTransactions = allTxBuf.map((txBuf) =>
        isV0Tx ? VersionedTransaction.deserialize(txBuf) : Transaction.from(txBuf)
      )

      console.log(`total ${allTransactions.length} transactions`, swapTransactions)

      let idx = 0
      if (!isV0Tx) {
        for (const tx of allTransactions) {
          console.log(`${++idx} transaction sending...`)
          const transaction = tx
          transaction.sign(owner)
          const txId = await sendAndConfirmTransaction(this.connection, transaction, [owner], { skipPreflight: true })
          console.log(`${++idx} transaction confirmed, txId: ${txId}`)
        }
      } else {
        for (const tx of allTransactions) {
          idx++
          const transaction = tx
          transaction.sign([this.ownWallet])
          const txId = await this.connection.sendTransaction(tx, { skipPreflight: true })
          const { lastValidBlockHeight, blockhash } = await this.connection.getLatestBlockhash({
            commitment: 'finalized',
          })
          console.log(`${idx} transaction sending..., txId: ${txId}`)
          await this.connection.confirmTransaction(
            {
              blockhash,
              lastValidBlockHeight,
              signature: txId,
            },
            'confirmed'
          )
          console.log(`${idx} transaction confirmed`)
        }
      }`

**Comment by cruzshia** [comment]
swap fee in demo code is using statistical fee amount to make swap tx, if you wish to set lower tx fee, you can set up desire fee amount here and pass to make swap api.
of course, it might cause lower confirmation possibility
```computeUnitPriceMicroLamports: String(here)```

**Comment by azizikheir1** [comment]
> swap fee in demo code is using statistical fee amount to make swap tx, if you wish to set lower tx fee, you can set up desire fee amount here and pass to make swap api. of course, it might cause lower confirmation possibility `computeUnitPriceMicroLamports: String(here)`

can you help with the implementation , the fee for a normal swap is 0.6$

**Comment by cruzshia** [comment]
As I said before, you can set up desired tx in param computeUnitPriceMicroLamports.
If you want to customize and lower your fee

const { data: swapTransactions } = await axios.post<{
    id: string
    version: string
    success: boolean
    data: { transaction: string }[]
  }>(`${API_URLS.SWAP_HOST}/transaction/swap-base-in`, {
    computeUnitPriceMicroLamports: String(data.data.default.h), // here
    swapResponse,
    txVersion,
    wallet: owner.publicKey.toBase58(),
    wrapSol: isInputSol,
    unwrapSol: isOutputSol, // true means output mint receive sol, false means output mint received wsol
    inputAccount: isInputSol ? undefined : inputTokenAcc?.toBase58(),
    outputAccount: isOutputSol ? undefined : outputTokenAcc?.toBase58(),
  })
